#!/bin/sh

err() { echo "$@" 1>&2; }
alias curl="wget -qO-"
API="https://api.deezer.com"
TYPES="(artist|album|track)"

self="$0"
if [ $# -eq 0 ]; then
	err "USAGE:\n	$0 $TYPES QUERY..."
	err "EXAMPLE:\n	$0 artist Queen\n	$0 album Greatest Hits\n	$0 track Innuendo"
	exit 1
fi

type="$1";shift
query=$(echo "$@" | tr ' ' +)
[ $type != track ] && limit="&limit=1" || limit="&limit=500"
id=$(curl "$API/search/$type?order=RANKING${limit}&strict=on&q=\"$query\"" | jq -r '.data[].id')
[ $type = artist ] && curl $API/$type/$id/top | jq -r ".data[].id"
[ $type = album ]  && curl $API/$type/$id     | jq -r ".tracks.data[].id"
[ $type = track ]  && echo $id


#if interactif (tty will be busy if mpv is also piped)
#alias dialog="$(which whiptail dialog) 3>&1 1>&2 2>&3"
#[ $type = track ]    && rule=".data[] | [.id,.title]|@sh"
#[ $type = album ]    && rule=".data[] | [.id,.title]|@sh"
#[ $type = artist ]   && rule=".data[] | [.id,.name ]|@sh"
#[ $type = playlist ] && rule=".data[] | [.id,.title]|@sh"
#id=$(curl $url | jq -r "$rule" | xargs whiptail 3>&1 1>&2 2>&3 --menu "title" 0 0 0)

